Added golang consumer and a machine identity for the consumer.

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,8 +1,15 @@
 #!/bin/bash
 
+set -e
+
+# Clean up environment
 docker-compose down
+
+# Build the consumer binary and Docker images
 docker-compose build
 
+# Start the conjur service
 docker-compose run --no-deps --rm conjur data-key generate > data_key
 export CONJUR_DATA_KEY="$(< data_key)"
 docker-compose up -d conjur
+docker-compose exec conjur conjurctl wait
